### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by arnalll** [LAGonauta/metahook#4] opened 2019-04-04 06:10 UTC
Hi,
first of all i want to thank you for your work.
with the last release i cant run Day of Defeat / error message is related to "out of memory". I have tested with a local compiled audio.dll and metahook but the result was the same.

thanks in advance

**Comment by LAGonauta** [comment] 2019-04-09 22:09
I will take a look, might be related to the new self-caching.

**Comment by LAGonauta** [comment] 2019-04-09 22:25
@arnalll 
Does it always happen? How can I reproduce?
A offline game is working here.

**Comment by arnalll** [comment] 2019-04-10 06:06
the exact error message is "OpenAL plugin error // unable to load. Rason: Failed to create AuxiliaryEffectSlot: Out of memory"
the game just try to launch but  crashes quite instantly
after your message i though maybe it was related to all new sounds i have put in the game and so i tested with regular sounds but the error still is the same.

SO basicaly with last release it happens all the time/ works all the time with the previous release of your plugin
i ve also tried without any other mod like metamod/amxmodx or even bots

i am using OpenAL/ for game related stuff it is steam up to date both half-life/ dod (last update is from few weeks).

**Comment by LAGonauta** [comment] 2019-04-10 10:11
Thanks, this error message was really helpful. This is happening because the OpenAL driver that you are current using does not support two effect slot at the same time (new smooth transition between effects). I managed to reproduce by using the "Software OpenAL" driver distributed by Creative. What driver are you using? Rapture3D? OpenAL Soft?
If you put the OpenAL32.dll (OpenAL Soft driver) file from the release package in the same folder as your metahook.exe the error should be fixed.
In the mean time I will decide if I will support smooth transition with limited drivers or not. In case you want to continue using your current OpenAL driver instead of OpenAL Soft, can you please elaborate why so?

**Comment by arnalll** [comment] 2019-04-10 17:29
thank you!
Solved.
i have no itention to use OpenAL instead of the soft one!

have a nice day

**Comment by LAGonauta** [comment] 2019-04-12 11:17
Good to know :)

**Closed by LAGonauta** 2019-04-12 11:17 UTC
